# Generated by Django 4.1.3 on 2022-12-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prretnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrretNum',
            new_name='PrretyNum',
        ),
    ]
