# Generated by Django 4.1.3 on 2023-02-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='usernaem',
            new_name='username',
        ),
    ]
